<a href="https://colab.research.google.com/github/niharika-123956/CODESOFT-TASK1/blob/main/Data_Analytics_task2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
import pandas as pd

df = pd.read_csv('mydata.csv')
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'mydata.csv'

In [ ]:
import pandas as pd

df = pd.read_csv("task2_data-1.csv")

df.head()

,Order_ID,Date,City,Product,Category,Quantity,Unit_Price,Discount,Total_Sales
0,1001,2026-01-05,Mumbai,Laptop,Electronics,2,45000,0.10,81000
1,1002,2026-01-07,Chennai,Mobile,Electronics,5,18000,0.05,85500
2,1003,2026-01-10,Hyderabad,Headphones,Accessories,10,2500,0.08,23000
3,1004,2026-01-12,Bengaluru,Laptop,Electronics,1,52000,0.05,49400
4,1005,2026-01-15,Delhi,Keyboard,Accessories,8,1800,0.10,12960

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order_ID     20 non-null     int64
 1   Date         20 non-null     object
 2   City         20 non-null     object
 3   Product      20 non-null     object
 4   Category     20 non-null     object
 5   Quantity     20 non-null     int64
 6   Unit_Price   20 non-null     int64
 7   Discount     20 non-null     float64
 8   Total_Sales  20 non-null     int64
dtypes: float64(1), int64(4), object(4)
memory usage: 1.5+ KB

In [ ]:
df.describe()

         Order_ID   Quantity    Unit_Price   Discount   Total_Sales
count    20.00000  20.000000     20.000000  20.000000     20.000000
mean   1010.50000   6.300000  22432.500000   0.071000  54526.750000
std       5.91608   5.554515  18666.634144   0.022688  28642.728492
min    1001.00000   1.000000    850.000000   0.050000  12825.000000
25%    1005.75000   2.000000   2575.000000   0.050000  29690.000000
50%    1010.50000   4.000000  20500.000000   0.065000  56440.000000
75%    1015.25000  10.000000  35250.000000   0.100000  81650.000000
max    1020.00000  20.000000  52000.000000   0.100000  89300.000000

In [ ]:
df.isnull().sum()

Order_ID       0
Date           0
City           0
Product        0
Category       0
Quantity       0
Unit_Price     0
Discount       0
Total_Sales    0
dtype: int64

In [ ]:
df.describe()

         Order_ID   Quantity    Unit_Price   Discount   Total_Sales
count    20.00000  20.000000     20.000000  20.000000     20.000000
mean   1010.50000   6.300000  22432.500000   0.071000  54526.750000
std       5.91608   5.554515  18666.634144   0.022688  28642.728492
min    1001.00000   1.000000    850.000000   0.050000  12825.000000
25%    1005.75000   2.000000   2575.000000   0.050000  29690.000000
50%    1010.50000   4.000000  20500.000000   0.065000  56440.000000
75%    1015.25000  10.000000  35250.000000   0.100000  81650.000000
max    1020.00000  20.000000  52000.000000   0.100000  89300.000000

In [ ]:
df.describe(include='object')